### ISSUE TITLE
MapGenerator Spec Incomplete

### ISSUE THREAD

**Issue by ghost** [Seneca-CDOT/thecollectors#45]
This issue is in reference to issue #41.

Currently the MapGenerator declaration file lists only one parameter that gets passed in during object instantiation: the game difficulty. From our earlier meetings, we had come up at least two more parameters that the MapGenerator needs: the number of delivery locations and the chance the fractions could be a multiple of the fuel denominator. I wish to know how these values fit into the generator, so that I can complete the code for #41.

Another thing I wanted to bring up was the validateMap function. I want to know if it is an external function to be called by the game after the generation of the map has been accomplished, or if this function is called internally by the generator itself. My current code reflects an external view, so the game has to handle the situation of the validation failing (by re-running the generator). It recursively calls the function that instantiates the generator to do it again if the map fails validation. If the validation is planned to be internal, then this check would not be necessary in the game logic itself. The game can be certain that the generator has a valid map by the time it needs it.

I may have more questions in the future but for now, these are the most pressing.

**Comment by dsegna** [comment]
The map validation should be done internally by the map generator, so that the map genreator can never generate an invalid map. There is no need for the game logic to have to deal with validate the map itself.

If you feel that you need to pass a certain parameter into the map generator while you are working with tutorial generation, feel free to assume that it will be supported, and let me know what it is. Currently the generator is in a very early, prototype stage, and is not using ANY parameters (not even the difficulty that is being passed in currently). As it is further developed I can add functionalities for the needed parameters without difficulty.
